### ISSUE TITLE
500 response on cart modification

### ISSUE THREAD

**Issue by TJTorola** [TJTorola/Samwise#2]
This was a response to saving a modified cart.
![image001](https://cloud.githubusercontent.com/assets/782134/16091927/acdcd9ec-32ea-11e6-9f0d-e24e735fb0ee.png)

**Comment by TJTorola** [comment]
Log output

`[2016-06-15 17:19:37] local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Fatal error: Call to a member function delete() on null in /home/forge/pangolin4x4.com/app/Http/Controllers/InvoicesController.php:160
Stack trace:
#0 [internal function]: App\Http\Controllers\InvoicesController->storeItems('1653', Object(App\Http\Requests\Invoices\StoreItemsRequest))
#1 /home/forge/pangolin4x4.com/bootstrap/cache/compiled.php(9372): call_user_func_array(Array, Array)
#2 /home/forge/pangolin4x4.com/bootstrap/cache/compiled.php(9434): Illuminate\Routing\Controller->callAction('storeItems', Array)
#3 /home/forge/pangolin4x4.com/bootstrap/cache/compiled.php(9414): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\InvoicesController), Object(Illuminate\Routing\Route), 'storeItems')
#4 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#5 /home/forge/pangolin4x4.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#6 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#7 /home/forge/pangolin4x4.com/bootstrap/cache/compiled.php(9891): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#8 /home/forge/pangolin4x4.com/bootstrap/cache/compiled.php(9415): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#9 /home/forge/pangolin4x4.com/bootstrap/cache/compiled.php(9402): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\InvoicesController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request$
#10 /home/forge/pangolin4x4.com/bootstrap/cache/compiled.php(8470): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\\Http\\Contro...', 'storeItems')
#11 /home/forge/pangolin4x4.com/bootstrap/cache/compiled.php(8457): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#12 /home/forge/pangolin4x4.com/bootstrap/cache/compiled.php(8171): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#13 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#14 /home/forge/pangolin4x4.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#15 /home/forge/pangolin4x4.com/app/Http/Middleware/Authenticate.php(52): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#16 [internal function]: App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure), 'invoices')
#17 /home/forge/pangolin4x4.com/bootstrap/cache/compiled.php(9906): call_user_func_array(Array, Array)
#18 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 /home/forge/pangolin4x4.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#20 /home/forge/pangolin4x4.com/app/Http/Middleware/Authenticate.php(52): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 [internal function]: App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 /home/forge/pangolin4x4.com/bootstrap/cache/compiled.php(9906): call_user_func_array(Array, Array)
#23 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 /home/forge/pangolin4x4.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#25 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 /home/forge/pangolin4x4.com/bootstrap/cache/compiled.php(9891): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#27 /home/forge/pangolin4x4.com/bootstrap/cache/compiled.php(8172): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#28 /home/forge/pangolin4x4.com/bootstrap/cache/compiled.php(8163): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#29 /home/forge/pangolin4x4.com/bootstrap/cache/compiled.php(8153): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#30 /home/forge/pangolin4x4.com/bootstrap/cache/compiled.php(2409): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#31 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#32 /home/forge/pangolin4x4.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#33 /home/forge/pangolin4x4.com/bootstrap/cache/compiled.php(3264): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#34 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /home/forge/pangolin4x4.com/bootstrap/cache/compiled.php(9906): call_user_func_array(Array, Array)`
